language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    - php: hhvm
      env: SYMFONY_VERSION=2.7.*

env:
    global:
        - LANG=en_US.UTF-8
install:
  - travis_retry composer require --no-interaction --prefer-source symfony/process:${SYMFONY_VERSION} symfony/filesystem:${SYMFONY_VERSION}

before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi

script:
  - ./vendor/bin/phpunit
